import { createUseStyles } from "react-jss";

const useStyles = createUseStyles({
  wrapper: {
    display: "flex",
    flexDirection: "row",
    gap: "20px",
  },
  summaryWrapper: {
    backgroundColor: "#D4D2B4",
    padding: "27px 91px 70px 91px",
    display: "flex",
    flexDirection: "column",
    maxWidth: "645px",
    width: "100%",
  },
  summaryText: {
    fontFamily: "Oswald, sans-serif",
    fontWeight: "400",
    fontSize: "18px",
    lineHeight: "26.68px",
    color: "black",
    marginBottom: "10px",
  },
  stackSummaryData: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  dataSummaryText: {
    fontFamily: "Source Serif 4, serif",
    fontWeight: "400",
    fontSize: "14px",
    lineHeight: "19.19px",
    color: "black",
    marginBottom: "15px",
    marginTop: "15px",
  },
  totalText: {
    fontFamily: "Source Serif 4, serif",
    fontWeight: "600",
    fontSize: "14px",
    lineHeight: "19.19px",
    color: "black",
    marginTop: "20px",
  },
  promoText: {
    fontFamily: "Source Serif 4, serif",
    fontWeight: "400",
    fontSize: "14px",
    lineHeight: "19.19px",
    color: "#686747",
    marginBottom: "15px",
    marginTop: "35px",
  },
  buttonCheckout: {
    width: "100%",
    height: "50px",
    backgroundColor: "#282826",
    fontFamily: "Oswald, sans-serif",
    fontWeight: "600",
    fontSize: "18px",
    lineHeight: "26.68px",
    color: "#F5F5F5",
  },
  container: {
    marginBottom: 56,
    padding: 0,
    minHeight: 1000,
  },
  line: {
    color: "black",
    height: "1px",
  },
  whiteCardWrapper: {
    width: "50px",
    height: "30px",
    border: "0.5px solid #282826",
    backgroundColor: "#FFFFFF",
    padding: "0px 2px",
  },
  cardsStack: {
    display: "flex",
    flexDirection: "row",
    gap: "10px",
    marginTop: "10px",
  },
  pinkCardWrapper: {
    width: "50px",
    height: "30px",
    border: "0.5px solid #282826",
    backgroundColor: "#FFB3C7",
    padding: "0px 2px",
  },
  cardImage: {
    width: "100%",
    height: "100%",
    objectFit: "contain",
  },
});
export default useStyles;
