import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
  container: {
    width: "645px",
    height: "814px",
    padding: "53px 111px 0px 111px",
    backgroundColor: "#D4D2B4",
  },
  textName: {
    fontFamily: "Oswald, sans-serif",
    fontSize: "18px",
    lineHeight: "26.68px",
    fontWeight: "400",
    color: "black",
    marginBottom: "0",
  },
  textTexture: {
    fontFamily: "Source Serif 4, serif",
    color: "#686747",
    fontWeight: "400",
    fontSize: "16px",
    lineHeight: "20.05px",
    marginTop: "5px",
    marginBottom: "0",
  },
  textPrice: {
    fontFamily: "Source Serif 4, serif",
    color: "black",
    fontWeight: "400",
    fontSize: "16px",
    marginTop: "20px",
    lineHeight: "20.05px",
    marginBottom: "0",
  },
  textParam: {
    fontFamily: "Source Serif 4, serif",
    color: "black",
    fontWeight: "400",
    fontSize: "16px",
    marginTop: "20px",
    marginBottom: "10px",
    lineHeight: "20.05px",
  },
  textGuide: {
    marginTop: "8px",
    fontFamily: "Source Serif 4, serif",
    cursor: "pointer",
    textDecoration: "underline",
    fontWeight: "400",
    fontSize: "16px",
    lineHeight: "20.05px",
    color: "black",
    marginBottom: "0",
  },
  buttonBag: {
    marginTop: "30px",
    backgroundColor: "#282826",
    height: "50px",
    width: "423px",
    fontSize: "18px",
    lineHeight: "26.68px",
    fontWeight: "600",
    fontFamily: "Oswald, sans-serif",
    color: "#F5F5F5",
    border: "0",
  },
  textDescription: {
    fontFamily: "Source Serif 4, serif",
    color: "black",
    fontWeight: "300",
    fontSize: "16px",
    marginBottom: "0",
    marginTop: "27px",
    lineHeight: "20.05px",
  },
  productAdditionalInfo: {
    marginTop: "20px",
  },
  stack: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
});
