import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
  container: {
    width: "645px",
    height: "814px",
    padding: "53px 111px 0px 111px",
    backgroundColor: "#D4D2B4",
  },
  textName: {
    fontFamily: "Oswald, sans-serif",
    fontSize: "18px",
    lineHeight: "26.68px",
    fontWeight: "400",
    color: "black",
    marginBottom: "0",
  },
  textTexture: {
    fontFamily: "Source Serif",
    color: "#686747",
    fontWeight: "400",
    fontSize: "16px",
    lineHeight: "20.05px",
    marginTop: "5px",
    marginBottom: "0",
  },
  textPrice: {
    fontFamily: "Source Serif",
    color: "black",
    fontWeight: "400",
    fontSize: "16px",
    marginTop: "20px",
    lineHeight: "20.05px",
    marginBottom: "0",
  },
  textParam: {
    fontFamily: "Source Serif",
    color: "black",
    fontWeight: "400",
    fontSize: "16px",
    marginTop: "20px",
    marginBottom: "10px",
    lineHeight: "20.05px",
  },
  textGuide: {
    marginTop: "8px",
    fontFamily: "Source Serif",
    cursor: "pointer",
    textDecoration: "underline",
    fontWeight: "400",
    fontSize: "16px",
    lineHeight: "20.05px",
    color: "black",
    marginBottom: "0",
  },
  buttonBag: {
    marginTop: "30px",
    backgroundColor: "#282826",
    height: "50px",
    width: "423px",
    fontSize: "18px",
    lineHeight: "26.68px",
    fontWeight: "600",
    fontFamily: "Oswald, sans-serif",
    color: "#F5F5F5",
    border: "0",
  },
  textDescription: {
    fontFamily: "Source Serif",
    color: "black",
    fontWeight: "300",
    fontSize: "16px",
    marginBottom: "0",
    marginTop: "27px",
    lineHeight: "20.05px",
  },
  productAdditionalInfo: {
    marginTop: "20px",
  },
  stack: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  select: {
    appearance: "none",
    WebkitAppearance: "none",
    MozAppearance: "none",
    width: "100%",
    height: "40px",
    fontWeight: "400",
    fontSize: "16px",

    paddingLeft: "11px",
    paddingRight: "24px",
    color: "black",
    fontFamily: "Source Serif",
    lineHeight: "20.05px",
    border: "1px solid black",
    backgroundColor: "#F5F5F5",
    borderRadius: "0",
    backgroundImage: `url("data:image/svg+xml,%3Csvg width='9' height='6' viewBox='0 0 9 6' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1 1L4.5 4.5L8 1' stroke='black'/%3E%3C/svg%3E")`,
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 8px center",
    "&:focus": {
      outline: "none",
      backgroundImage: `url("data:image/svg+xml,%3Csvg width='9' height='5' viewBox='0 0 9 5' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1 4.5L4.5 1L8 4.5' stroke='black'/%3E%3C/svg%3E")`,
    },
  },
  option: {
    borderRadius: 0,
    height: "40px",
    border: 0,
  },
});
