import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
  headerWrapper: {
    height: "60px",
    position: "fixed",
    zIndex: "1000",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    padding: "14px 65px",
    borderBottom: "1px solid black",
    backgroundColor: "#FFFFFF",
  },
  lineHeader: {
    color: "black",
    height: "1px",
    opacity: "1",
    width: "100%",
    position: "absolute",
    bottom: "0",
  },
  headerText: {
    fontFamily: "Source Serif",
    fontWeight: "400",
    fontSize: "18px",
    margin: 0,
    textDecoration: "none",
    lineHeight: "22.55px",
    color: "black",
  },
  leftWrapper: {
    height: "100%",
    padding: "80px 20px 57px 65px",
    maxWidth: "841px",
    width: "100%",
  },
  contentWrapper: {
    paddingTop: "60px",
    display: "flex",
    justifyContent: "center",
    flexDirection: "row",
    height: "100%",
    minHeight: "100vh",
    width: "100%",
    flexWrap: "wrap",
  },
  //right side
  rightWrapper: {
    maxHeight: "2204px",
    backgroundColor: "#D4D2B4",
    maxWidth: "599px",
    width: "100%",
    padding: "27px 65px",
  },
  subtotalMargin: {
    marginBottom: "15px",
  },
  dataSummaryText: {
    fontFamily: "Source Serif 4",
    fontWeight: "400",
    fontSize: "14px",
    lineHeight: "19.19px",
    color: "black",
    margin: 0,
  },
  totalText: {
    fontFamily: '"Source Serif 4", serif',
    fontWeight: "600",
    fontSize: "14px",
    lineHeight: "19.19px",
    color: "black",
  },
  stackSummaryData: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  line: {
    color: "black",
    height: "1px",
    opacity: "1",
  },
  summaryText: {
    fontFamily: "Oswald, sans-serif",
    fontWeight: "400",
    fontSize: "18px",
    lineHeight: "26.68px",
    color: "black",
    margin: 0,
  },
  //left side
  emailText: {
    fontFamily: '"Source Serif 4", serif',
    fontWeight: "400",
    fontSize: "18px",
    lineHeight: "24.68px",
    color: "black",
    marginBottom: "56px",
  },
  container: {
    display: "flex",
    flexDirection: "column",
  },
  textValidation: {
    color: "#C10000",
    fontSize: "11px",
    lineHeight: "13.78px",
    fontFamily: "Source Serif",
  },
  validationInput: {
    display: "flex",
    flexDirection: "column",
  },
  inputMain: {
    border: "none",
    borderBottom: " 1px solid #282826",
    padding: "5px 0px",
    backgroundColor: "transparent",
    outline: "none",
    width: "368px",
    "&::placeholder": {
      color: "#585852",
      fontFamily: "Source Serif",
      fontSize: "14px",
      lineHeight: "17.54px",
      fontWeight: "400",
    },
  },
  termsWrapper: {
    display: "flex",
    flexDirection: "row",
    gap: "10px",
    alignItems: "flex-start",
  },
  checkboxTerms: {
    marginTop: "5px",
    "&:checked": {
      backgroundColor: "red",
    },
  },
  textTerms: {
    color: "black",
    fontSize: "16px",
    fontWeight: "400",
    lineHeight: "21.94px",
    fontFamily: "Source Serif",
    marginBottom: "17px",
  },
  buttonConfirm: {
    marginTop: "40px",
    width: "356px",
    height: "50px",
    backgroundColor: "#282826",
    fontFamily: "Oswald, sans-serif",
    fontWeight: "600",
    fontSize: "18px",
    lineHeight: "26.68px",
    color: "#F5F5F5",
    margin: "0 auto",
  },
});
